import { Inter, Lora, Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import GlobalScrollReveal from "@/components/GlobalScrollReveal";


const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  weight: ["400", "500", "600", "700"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${manrope.variable}`}
    >
      <body className="min-h-full flex flex-col">

        <SmoothScroll>
          <GlobalScrollReveal />

          <main>
            {children}
          </main>
        </SmoothScroll>
      </body>
    </html>
  );
}
